# Generated by Django 5.1.5 on 2025-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
